### PR TITLE
 #227 beware of platform precision problems in unit test

### PR DESCRIPTION
**Pull request by Husterknupp**
thanks for the introduction señor :dancer:

### CODE REVIEW

**Comment by FRosner** [comment]
Shoot, @Husterknupp. My sbt task for automatically uploading the master branch as a snapshot jar to S3 caused the build to fail. So we have two options. Either, you recreate the pull request on a feature branch instead (so the build does not trigger the upload), or I need to find a way to tell sbt that it is a pull request that is being build.

#### [Travis CI Documentation](http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests)

> Rather than test the commits from the branches the pull request is sent from, we test the merge between the origin and the upstream branch.
> 
> The environment variable ${TRAVIS_PULL_REQUEST} is set to "false" when the build is for a normal branch commit. When the build is for a pull request, it will contain the pull request’s number.

```
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bundle exec rake tests:integration || false'
```

**Comment by Husterknupp** [comment]
Why did the automatic uploading fail? Was it because Travis' output was only the merged lines of code?

**Comment by FRosner** [comment]
It is because for uploading (which anyway should only happen to merged branches and not pull requests), you need a key. This key is for obvious reasons only visible to builds triggered directly from my repository. Otherwise you could gain access to my S3 bucket. 

## I will fix it and would like you to recreate the pull request then to make sure that it worked :-)

Sent from my phone. Please excuse my brevity.

Benjamin Schandera notifications@github.com wrote:

Why did the automatic uploading fail? Was it because Travis' output was only the merged lines of code?

**Comment by FRosner** [comment]
@Husterknupp can you please rebase your master against mine so the pull request gets reissued with the fix from #257?

If you cannot do it due to time constraints, let me know.

**Comment by Husterknupp** [comment]
Hey @FRosner thanks for keeping me updated. I will find time this or the next week.

**Comment by FRosner** [comment]
What's the status on this guy @Husterknupp?

**Comment by Husterknupp** [comment]
Hey @FRosner I lost track a bit :palm_tree: 

I rebased my master against your master. Also all unit tests passed. I dont see Travis executing his checks.. I guess you need to trigger them manually?

**Comment by FRosner** [comment]
Did you push your changes? If you rebase, you might have to force push.

Then the PR should automatically pick up the changes to your branch?

**Comment by Husterknupp** [comment]
Yessir. I rebased my master against your master and had no merge conflicts. After that I force pushed my local master to my remote master.

find a863eeeb in https://github.com/Husterknupp/spawncamping-dds/commits/master

**Comment by FRosner** [comment]
And Travis is checking, no?

**Comment by Husterknupp** [comment]
Github is saying below .. including yellow bubble

> Some checks haven’t completed yet
> 1 expected check
> Required  continuous-integration/travis-ci — Waiting for status to be reported

**Comment by FRosner** [comment]
"Some check haven't completed yet" usually means, that Travis is still running... I am not sure. But it might be because you did something funny when rebasing, because instead of putting your commit on top you put mine on top and committed them as yours.

**Comment by FRosner** [comment]
Let's do a screen sharing to resolve this problem tomorrow? Or you can just reset your branch and recommit, as it is only a small change. Or I can simply cherry-pick your commit if this works for you.

LMK

**Comment by Husterknupp** [comment]
wait now I see Travis executing a check. I think because my git status said something about being not up-to-date, after I rebased against your master, I again rebased against my master before I force pushed. Which put my test fix commit not on top of your master but rather back at my master + 1. Forgot to put on my smarty pants

Anyway, it should be good now.

**Comment by RPCMoritz** [comment]
Good job!

**Pull request merged**
